contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #cioabcdpipeline channel"
    url: https://nfcore.slack.com/channels/cioabcdpipeline
    about: Discussion about the nf-core/cioabcdpipeline pipeline
